Repository JasonN3/build-container-installer, pull requests merged in 2024-03, with the labels that each got.

#27 Remove need for action_version
  .github/workflows/build-and-test.yml
  README.md
  action.yml
Labels: enhancement, breaking-change

#30 Use Skopeo instead of Podman
  Makefile
Labels: enhancement

#33 Use bootc when available
  Makefile
  lorax_templates/configure_upgrades.tmpl.in
  lorax_templates/scripts/post/configure_upgrades
Labels: enhancement

#34 Ensure workspace dir is used and not current dir
  action.yml
Labels: bug

#26 ci: Test resulting test ISO
  .github/workflows/build-and-test.yml
  Makefile
  tests/iso/README.md
  tests/iso/os-release.sh
  tests/vm/README.md
Labels: enhancement, ignore-for-release

#40 Fix bootc command
  lorax_templates/scripts/post/configure_upgrades
Labels: enhancement

#35 Add support for extra boot options
  Makefile
  xorriso/gen_input.sh.in
Labels: enhancement

#41 Fix Container Copying to Directory
  .github/workflows/build-and-test.yml
  Containerfile
  Makefile
  README.md
  action.yml
  entrypoint.sh
Labels: enhancement

#32 Add flatpaks
  .github/workflows/build-and-test.yml
  .gitmodules
  Makefile
  README.md
  action.yml
  entrypoint.sh
  lorax_templates/scripts/post/configure_flatpak
  lorax_templates/set_flatpak_repo.tmpl.in
  tests/iso/os-release.sh
  tests/iso/verify_flatpakrepo_updated.sh
  tests/vm/flatpak.yml
Labels: enhancement

#46 Allow caching of dnf
  .gitignore
  Containerfile
  Makefile
  README.md
  action.yml
  entrypoint.sh
  lorax_templates/cache_copy_dnf.tmpl
  lorax_templates/flatpak_set_repo.tmpl
  lorax_templates/install_set_installer.tmpl
  lorax_templates/scripts/post/flatpak_configure
  lorax_templates/scripts/post/install_configure_upgrades
  lorax_templates/scripts/post/secureboot_enroll_key
  lorax_templates/set_installer.tmpl.in
Labels: enhancement

#56 Fix var reference
  action.yml
Labels: bug

#61 Fixes macros still being readable
  Makefile
  action.yml
Labels: bug

#63 Fix builds on main
  action.yml
Labels: bug

#62 Prep for Anaconda 41
  Makefile
  lorax_templates/flatpak_set_repo.tmpl
Labels: enhancement

#66 Allowing storing the Flatpak refs in files
  .github/workflows/build-and-test.yml
  Makefile
  README.md
  action.yml
  flatpak_refs/VLC
  lorax_templates/flatpak_set_repo.tmpl
  tests/iso/flatpak_repo_updated.sh
  tests/iso/install_os-release.sh
  tests/vm/flatpak_update.yml
Labels: enhancement

#68 Add stale workflow
  .github/workflows/stale.yml
Labels: enhancement, ignore-for-release

#69 Only run some actions on 38 or older
  .github/workflows/build-and-test.yml
  .gitignore
  Makefile
  lorax_templates/scripts/post/install_configure_upgrades
Labels: bug

#72 flatpak_set_repo fails to load
  .github/workflows/build-and-test.yml
  Makefile
  action.yml
  flatpak_refs/Firefox
  lorax_templates/flatpak_set_repo.tmpl
Labels: bug

#75 Revert chmod command on build directory
  entrypoint.sh
Labels: bug

#70 Fix post scripts and use multiple OS versions in tests
  .github/workflows/build-and-test.yml
  Makefile
  README.md
  tests/vm/flatpak_update.yml
Labels: bug, enhancement

#78 Fix service being disabled in runtime instead of resulting OS
  lorax_templates/flatpak_set_repo.tmpl
  lorax_templates/scripts/post/flatpak_configure
Labels: bug

#76 Add tests
  .github/workflows/bot_run_tests.yml
  .github/workflows/build-and-test.yml
  .github/workflows/variables.yml
  Makefile
  README.md
  action.yml
  lorax_templates/flatpak_set_repo.tmpl
  lorax_templates/scripts/post/flatpak_configure
  tests/repo/vars.sh
  tests/vm/flatpak_fedora_repo_disabled.yml
  tests/vm/flatpak_installed.yml
  tests/vm/install_image_source.yml
Labels: enhancement, auto-test

#79 Split Tests to Separate files
  .github/workflows/bot_commands.yml
  .github/workflows/bot_run_tests.yml
  .github/workflows/build-and-test.yml
  .github/workflows/build_container.yml
  .github/workflows/build_iso.yml
  .github/workflows/build_vars.yml
  .github/workflows/test_deployment.yml
  .github/workflows/test_iso.yml
  .github/workflows/tests.yml
Labels: enhancement, ignore-for-release

#80 Fix tests for PRs
  .github/workflows/bot_commands.yml
  .github/workflows/build_container.yml
  .github/workflows/build_iso.yml
  .github/workflows/build_vars.yml
  .github/workflows/test_deployment.yml
  .github/workflows/test_iso.yml
  .github/workflows/tests.yml
Labels: bug, ignore-for-release

#83 fix repo reference
  action.yml
Labels: bug

#84 Fix issues pulling from fork build
  .github/workflows/build_iso.yml
Labels: bug

#87 Add run build iso command to bot commands
  .github/workflows/bot_commands.yml
Labels: enhancement, ignore-for-release

#86 Automatically determine Flatpak dependencies
  .github/workflows/build_container.yml
  .github/workflows/build_iso.yml
  .gitignore
  Makefile
  action.yml
  flatpak_refs/Firefox
  flatpak_refs/VLC
  lorax_templates/flatpak_link.tmpl
  xorriso/gen_input.sh.in
Labels: enhancement

#90 Fix version tag
  .github/workflows/build_container.yml
Labels: bug

#91 Delete untagged packages
  .github/workflows/clean_repo.yml
Labels: enhancement, ignore-for-release

#92 Clean repo of old packages
  .github/workflows/clean_repo.yml
  .github/workflows/stale.yml
Labels: enhancement, ignore-for-release
